# Generated by Django 3.2.12 on 2022-11-28 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_alter_organization_organization_type'),
        ('Documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('ClaimID', models.PositiveIntegerField()),
                ('Amount', models.PositiveIntegerField()),
                ('Success', models.BooleanField(default=False)),
                ('Reciever', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Reciever', to='authentication.custom_user')),
                ('Sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Sender', to='authentication.custom_user')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance_Claims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_type', models.CharField(choices=[('Insurance', 'Insurance'), ('Pharmacy', 'Pharmacy')], max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('system_approved', models.BooleanField(default=False)),
                ('amount', models.PositiveIntegerField(null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='Documents.document')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firm', to='authentication.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='authentication.patient')),
            ],
        ),
    ]
