# Generated by Django 3.2.12 on 2022-11-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance_claims',
            name='firm_type',
            field=models.CharField(choices=[('Pharmacy', 'Pharmacy'), ('Insurance', 'Insurance')], max_length=20),
        ),
    ]
