# Generated by Django 4.1.2 on 2022-11-27 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20221106_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='certificate_pass',
            field=models.CharField(default='yGLN43npQvXz3enw5Hcx', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('Insurance', 'Insurance'), ('Pharmacy', 'Pharmacy'), ('Hospital', 'Hospital')], default='Hospital', max_length=20),
        ),
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_key', models.CharField(default=None, max_length=1024, unique=True)),
                ('priv_key', models.CharField(default=None, max_length=1024, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.custom_user')),
            ],
        ),
    ]
