# Generated by Django 4.1.2 on 2022-11-27 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_custom_user_certificate_pass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='certificate_pass',
            field=models.CharField(default='nbYzbTQNgM3dEzHgdEky', max_length=20),
        ),
        migrations.AlterField(
            model_name='keys',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.custom_user', unique=True),
        ),
    ]
