# Generated by Django 4.1.2 on 2022-11-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_custom_user_certificate_pass_alter_keys_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='certificate_pass',
            field=models.CharField(default='VwGzzJbwbBmjaNt6D4wB', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('Hospital', 'Hospital'), ('Pharmacy', 'Pharmacy'), ('Insurance', 'Insurance')], default='Hospital', max_length=20),
        ),
    ]
