# Generated by Django 3.2.12 on 2022-11-28 14:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_alter_organization_organization_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(max_length=256, upload_to='Documents', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('verification_username', models.CharField(blank=True, max_length=50)),
                ('verification_user_type', models.CharField(blank=True, max_length=50)),
                ('owner_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.patient')),
                ('shared_with_doctors', models.ManyToManyField(blank=True, to='authentication.Doctor')),
                ('shared_with_organization', models.ManyToManyField(blank=True, to='authentication.Organization')),
            ],
        ),
    ]
