# Generated by Django 3.2.12 on 2022-11-01 10:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('owner_patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.patient')),
                ('shared_with_doctors', models.ManyToManyField(blank=True, to='authentication.doctor')),
                ('shared_with_hospital', models.ManyToManyField(blank=True, to='authentication.hospital')),
                ('shared_with_insurance_firm', models.ManyToManyField(blank=True, to='authentication.insurance_firm')),
                ('shared_with_pharmacy', models.ManyToManyField(blank=True, to='authentication.pharmacy')),
            ],
        ),
    ]
