# Generated by Django 3.2.12 on 2022-10-31 18:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0004_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('owner_patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Authentication.patient')),
                ('shared_with_doctors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.doctor')),
                ('shared_with_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.hospital')),
                ('shared_with_insurance_firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.insurance_firm')),
                ('shared_with_pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.pharmacy')),
            ],
        ),
    ]
