# Generated by Django 3.2.12 on 2022-11-01 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('Documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='owner_patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.patient'),
        ),
    ]
