# Generated by Django 3.2.12 on 2022-10-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_delete_document'),
        ('Documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='shared_with_doctors',
        ),
        migrations.AddField(
            model_name='document',
            name='shared_with_doctors',
            field=models.ManyToManyField(to='Authentication.doctor'),
        ),
        migrations.RemoveField(
            model_name='document',
            name='shared_with_hospital',
        ),
        migrations.AddField(
            model_name='document',
            name='shared_with_hospital',
            field=models.ManyToManyField(to='Authentication.hospital'),
        ),
        migrations.RemoveField(
            model_name='document',
            name='shared_with_insurance_firm',
        ),
        migrations.AddField(
            model_name='document',
            name='shared_with_insurance_firm',
            field=models.ManyToManyField(to='Authentication.insurance_firm'),
        ),
        migrations.RemoveField(
            model_name='document',
            name='shared_with_pharmacy',
        ),
        migrations.AddField(
            model_name='document',
            name='shared_with_pharmacy',
            field=models.ManyToManyField(to='Authentication.pharmacy'),
        ),
    ]
