# Generated by Django 3.2.12 on 2022-11-01 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0002_alter_document_owner_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='verification_user_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='verification_username',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=256, upload_to='Documents', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
