# Generated by Django 3.2.12 on 2022-11-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='certificate_pass',
            field=models.CharField(default='cXFnsykHwjLjYRhzhJ5E', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('Pharmacy', 'Pharmacy'), ('Insurance', 'Insurance'), ('Hospital', 'Hospital')], default='Hospital', max_length=20),
        ),
    ]
