# Generated by Django 3.2.12 on 2022-11-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('Insurance', 'Insurance'), ('Pharmacy', 'Pharmacy'), ('Hospital', 'Hospital')], default='Hospital', max_length=20),
        ),
    ]
