# Generated by Django 4.1.2 on 2022-10-30 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Authentication.organization')),
            ],
            bases=('Authentication.organization',),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('document', models.FileField(blank=True, upload_to='doc')),
            ],
        ),
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Authentication.organization')),
            ],
            bases=('Authentication.organization',),
        ),
        migrations.CreateModel(
            name='insurance_firm',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Authentication.organization')),
            ],
            bases=('Authentication.organization',),
        ),
        migrations.CreateModel(
            name='pharmacy',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Authentication.organization')),
            ],
            bases=('Authentication.organization',),
        ),
        migrations.RemoveField(
            model_name='organization',
            name='name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='hello', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='mydoctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Authentication.doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='myhospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Authentication.hospital'),
        ),
        migrations.AddField(
            model_name='patient',
            name='myinsurance_firm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Authentication.insurance_firm'),
        ),
    ]
