# Generated by Django 3.2.12 on 2022-11-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20221104_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='certificate_pass',
            field=models.CharField(default='Jf3bZVhggfFcUfXr5zG6', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('Hospital', 'Hospital'), ('Insurance', 'Insurance'), ('Pharmacy', 'Pharmacy')], default='Hospital', max_length=20),
        ),
    ]
