# Generated by Django 3.2.12 on 2022-11-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20221106_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='certificate_pass',
            field=models.CharField(default='GWP2v9N2T2zXpLGgwW2Z', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('Hospital', 'Hospital'), ('Insurance', 'Insurance'), ('Pharmacy', 'Pharmacy')], default='Hospital', max_length=20),
        ),
    ]
