# Generated by Django 4.1.2 on 2022-10-31 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_doctor_document_hospital_insurance_firm_pharmacy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document',
            new_name='doc',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='document',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mydoctor',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='myhospital',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='myinsurance_firm',
        ),
        migrations.AddField(
            model_name='document',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Authentication.patient'),
        ),
    ]
