# Generated by Django 4.1.2 on 2022-10-31 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_document_document_doc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pending_doctor',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.organization')),
                ('license_number', models.CharField(max_length=10)),
            ],
            bases=('authentication.organization',),
        ),
        migrations.CreateModel(
            name='pending_organization',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.user')),
                ('description', models.CharField(max_length=500)),
                ('image_1', models.ImageField(max_length=254, upload_to=None)),
                ('image_2', models.ImageField(max_length=254, upload_to=None)),
                ('image_3', models.ImageField(blank=True, max_length=254, upload_to=None)),
                ('image_4', models.ImageField(blank=True, max_length=254, upload_to=None)),
                ('image_5', models.ImageField(blank=True, max_length=254, upload_to=None)),
            ],
            bases=('authentication.user',),
        ),
        migrations.CreateModel(
            name='pending_patient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.user')),
                ('aadhar', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('id_proof', models.FileField(max_length=254, upload_to='Patient_ID')),
            ],
            bases=('authentication.user',),
        ),
        migrations.AddField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(default=22, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='id_proof',
            field=models.FileField(default='None/Blank.png', max_length=254, upload_to='Patient_ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
    ]
