# Generated by Django 3.2.12 on 2022-10-31 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_rename_document_document_doc_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
