# Generated by Django 4.1.2 on 2022-11-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20221106_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='certificate_pass',
            field=models.CharField(default='CHQfmzGDve4Z7nVmtHPQ', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('Hospital', 'Hospital'), ('Pharmacy', 'Pharmacy'), ('Insurance', 'Insurance')], default='Hospital', max_length=20),
        ),
    ]
