# Generated by Django 3.2.12 on 2022-11-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block_Chain',
            fields=[
                ('block_id', models.AutoField(primary_key=True, serialize=False)),
                ('block', models.CharField(max_length=50000)),
            ],
        ),
    ]
